services:
  
  prefect-server:
    image: prefecthq/prefect:2-latest 
    command: prefect server start --host 0.0.0.0 
    ports:
      - "4200:4200"
    environment:
      PREFECT_LOGGING_LEVEL: INFO
      PROJECT_ROOT: /app
      STREAMLIT_SHOW_WARNING_ON_DIRECT_EXECUTION: "false"
    volumes:
      - prefect-server-data:/root/.prefect
      - .:/app
    restart: always 

  prefect-agent:
    build:
      context: .
      dockerfile: Dockerfile.agent 
    depends_on:
      prefect-server:
        condition: service_started
    command: >
      /bin/bash -c "
        echo 'Waiting for Prefect server to be ready before initialization and deployment...'
        sleep 15; 
        echo 'Attempting to create work pool default-agent-pool...'
        prefect work-pool create 'default-agent-pool' || echo 'Work pool already exists or creation failed (ignored).'
        echo 'Work pool creation command finished.'
        echo 'Attempting to build and apply deployment marketing-pipeline-docker...'
        cd /app && PREFECT_ORION_URL=http://prefect-server:4200/api prefect deployment build /app/scripts/run_pipeline.py:marketing_pipeline_flow --name marketing-pipeline-docker --apply --override env.PROJECT_ROOT=\"/app\" || echo 'Deployment failed (ignored).'
        echo 'Deployment command finished.'
        echo 'Starting agent...'
        prefect agent start --pool 'default-agent-pool'
      "
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api 
      PYTHONPATH: /app
      PROJECT_ROOT: /app
      STREAMLIT_SHOW_WARNING_ON_DIRECT_EXECUTION: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - prefect-agent-data:/root/.prefect
      - .:/app
    restart: always 

  watchdog-monitor:
    
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api 
      PYTHONPATH: /app
      PROJECT_ROOT: /app 
      PREFECT_DEPLOYMENT_NAME: marketing-pipeline-docker
      PREFECT_FLOW_NAME: Marketing Analytics Pipeline
    volumes:
      - .:/app
    depends_on:
      prefect-server:
        condition: service_started
    command: python scripts/monitor_data.py

volumes:
  prefect-server-data: 
  prefect-agent-data: 
