ARG PREFECT_VERSION=2.8.2
ARG PYTHON_VERSION=3.10
FROM prefecthq/prefect:${PREFECT_VERSION}-python${PYTHON_VERSION}

WORKDIR /app

COPY requirements.txt /app/requirements.txt
COPY src /app/src
COPY scripts /app/scripts
COPY data /app/data
COPY config /app/config
COPY .prefectignore /app/.prefectignore

RUN pip install --no-cache-dir -r /app/requirements.txt


ENV PYTHONPATH=/app

