# .github/workflows/test.yml

name: Run Tests

on:
  push:
    branches:
      - main  # Or your main branch name, e.g., 'master'
  pull_request:
    branches:
      - main  # Or your main branch name

jobs:
  test:
    runs-on: ubuntu-latest # Use a recent version of Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Use v4 for checkout action

    - name: Set up Python
      # Use the Python version specified in your requirements or commonly used in your project
      uses: actions/setup-python@v5 # Use v5 for setup-python action
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest
      # The command to run your tests
      # Assuming pytest is installed via requirements.txt and tests are in the ./tests directory
      run: |
        pytest ./tests

